import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'category',
      label: 'Module 1: Foundations',
      link: {
        type: 'generated-index',
        title: 'Module 1 Overview',
        description: 'Fundamentals of Physical AI and robotics.',
        slug: '/module-1-foundations', // Updated slug
      },
      items: [
        {
          type: 'category',
          label: 'Week 1: AI Fundamentals',
          link: {
            type: 'generated-index',
            title: 'Week 1 Overview',
            description: 'Core concepts for the first week.',
            slug: '/module-1-foundations/week-1-ai-fundamentals', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-1-foundations/week-1-ai-fundamentals'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 2: Robot Movement',
          link: {
            type: 'generated-index',
            title: 'Week 2 Overview',
            description: 'Understanding robot movement.',
            slug: '/module-1-foundations/week-2-robot-movement', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-1-foundations/week-2-robot-movement'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 3: Dynamics & Actuators',
          link: {
            type: 'generated-index',
            title: 'Week 3 Overview',
            description: 'Forces and motion in robotics.',
            slug: '/module-1-foundations/week-3-dynamics-actuators', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-1-foundations/week-3-dynamics-actuators'}], // Updated dirName
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Perception',
      link: {
        type: 'generated-index',
        title: 'Module 2 Overview',
        description: 'How robots perceive their environment.',
        slug: '/module-2-perception', // Updated slug
      },
      items: [
        {
          type: 'category',
          label: 'Week 4: World Sensing',
          link: {
            type: 'generated-index',
            title: 'Week 4 Overview',
            description: 'Types and applications of robot sensors.',
            slug: '/module-2-perception/week-4-world-sensing', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-2-perception/week-4-world-sensing'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 5: Visual Data',
          link: {
            type: 'generated-index',
            title: 'Week 5 Overview',
            description: 'Processing visual data for robots.',
            slug: '/module-2-perception/week-5-visual-data', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-2-perception/week-5-visual-data'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 6: Robot Location',
          link: {
            type: 'generated-index',
            title: 'Week 6 Overview',
            description: 'Robots knowing where they are.',
            slug: '/module-2-perception/week-6-robot-location', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-2-perception/week-6-robot-location'}], // Updated dirName
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Control & Navigation',
      link: {
        type: 'generated-index',
        title: 'Module 3 Overview',
        description: 'Making robots move intelligently.',
        slug: '/module-3-control-navigation', // Updated slug
      },
      items: [
        {
          type: 'category',
          label: 'Week 7: Pathfinding',
          link: {
            type: 'generated-index',
            title: 'Week 7 Overview',
            description: 'Algorithms for robot navigation.',
            slug: '/module-3-control-navigation/week-7-pathfinding', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-3-control-navigation/week-7-pathfinding'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 8: Smooth Motion',
          link: {
            type: 'generated-index',
            title: 'Week 8 Overview',
            description: 'Smooth and efficient robot movements.',
            slug: '/module-3-control-navigation/week-8-smooth-motion', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-3-control-navigation/week-8-smooth-motion'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 9: Orchestrating Control',
          link: {
            type: 'generated-index',
            title: 'Week 9 Overview',
            description: 'Designing effective control systems.',
            slug: '/module-3-control-navigation/week-9-orchestrating-control', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-3-control-navigation/week-9-orchestrating-control'}], // Updated dirName
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Humanoids & Ethics',
      link: {
        type: 'generated-index',
        title: 'Module 4 Overview',
        description: 'The convergence of AI and humanoid robots.',
        slug: '/module-4-humanoids-ethics', // Updated slug
      },
      items: [
        {
          type: 'category',
          label: 'Week 10: Human-Robot Collaboration',
          link: {
            type: 'generated-index',
            title: 'Week 10 Overview',
            description: 'Designing robots for human collaboration.',
            slug: '/module-4-humanoids-ethics/week-10-human-robot-collaboration', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-4-humanoids-ethics/week-10-human-robot-collaboration'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 11: Robot Learning',
          link: {
            type: 'generated-index',
            title: 'Week 11 Overview',
            description: 'Machine learning techniques for robots.',
            slug: '/module-4-humanoids-ethics/week-11-robot-learning', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-4-humanoids-ethics/week-11-robot-learning'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 12: Humanoid Design',
          link: {
            type: 'generated-index',
            title: 'Week 12 Overview',
            description: 'Latest developments in humanoid robot design.',
            slug: '/module-4-humanoids-ethics/week-12-humanoid-design', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-4-humanoids-ethics/week-12-humanoid-design'}], // Updated dirName
        },
        {
          type: 'category',
          label: 'Week 13: Future & Ethics',
          link: {
            type: 'generated-index',
            title: 'Week 13 Overview',
            description: 'The impact of advanced robotics on society.',
            slug: '/module-4-humanoids-ethics/week-13-future-ethics', // Updated slug
          },
          items: [{type: 'autogenerated', dirName: 'module-4-humanoids-ethics/week-13-future-ethics'}], // Updated dirName
        },
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      link: {
        type: 'doc',
        id: 'glossary',
      },
      items: [{type: 'autogenerated', dirName: 'glossary'}],
    },
  ],
};

export default sidebars;
