"""
Base data models for the Book RAG Chatbot.
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
import datetime

class BaseResponse(BaseModel):
    """Base response model with common fields"""
    id: str
    timestamp: datetime.datetime = Field(default_factory=datetime.datetime.now)
    success: bool = True

class UserQuery(BaseModel):
    """Model representing a user's question or request to the system"""
    id: str
    text: str = Field(..., min_length=1, max_length=1000)
    selected_chunks: Optional[List[str]] = Field(default_factory=list)
    timestamp: datetime.datetime = Field(default_factory=datetime.datetime.now)
    session_id: Optional[str] = None

class RetrievedPassage(BaseModel):
    """Model representing a retrieved text segment from the vector database"""
    chunk_id: str
    document_id: str
    content: str
    similarity_score: float
    source_url: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class Evidence(BaseModel):
    """Model for source citation included in responses"""
    doc_id: str = Field(..., description="Document identifier where the information was found")
    chunk_id: str = Field(..., description="Chunk identifier within the document")
    quote: str = Field(..., max_length=1000, description="Verbatim quote or relevant excerpt (≤1000 characters)")
    source_url: Optional[str] = None

class Response(BaseModel):
    """Model for the structured output containing both JSON schema and human-readable answer with citations"""
    id: str
    query_id: str
    answer: str = Field(..., description="The main answer text generated by the system")
    evidence: List[Evidence] = Field(default_factory=list, description="List of evidence objects containing source citations")
    confidence: str = Field(..., pattern=r"^(High|Medium|Low)$", description="Confidence level (High|Medium|Low)")
    follow_up: Dict[str, Any] = Field(..., description="Optional follow-up question suggestion")
    timestamp: datetime.datetime = Field(default_factory=datetime.datetime.now)