"""
Response model for the Book RAG Chatbot.
"""
from pydantic import BaseModel, Field, field_validator
from typing import List, Dict, Any
import datetime
from .base import Evidence

class Response(BaseModel):
    """Model for the structured output containing both JSON schema and human-readable answer with citations"""
    id: str = Field(..., description="Unique identifier for the response")
    query_id: str = Field(..., description="Reference to the original user query")
    answer: str = Field(..., description="The main answer text generated by the system")
    evidence: List[Evidence] = Field(
        default_factory=list,
        description="List of evidence objects containing source citations"
    )
    confidence: str = Field(
        ...,
        pattern=r"^(High|Medium|Low)$",
        description="Confidence level (High|Medium|Low)"
    )
    follow_up: Dict[str, Any] = Field(
        ...,
        description="Optional follow-up question suggestion"
    )
    timestamp: datetime.datetime = Field(
        default_factory=datetime.datetime.now,
        description="When the response was generated"
    )
    json_schema: Dict[str, Any] = Field(
        default_factory=dict,
        description="The complete response in the required JSON format"
    )

    class Config:
        # Allow extra fields for flexibility
        extra = "allow"

    @field_validator('evidence')
    @classmethod
    def validate_evidence_quotes(cls, v):
        """Validate that all evidence quotes are ≤1000 characters"""
        for evidence_item in v:
            if hasattr(evidence_item, 'quote') and len(evidence_item.quote) > 1000:
                raise ValueError(f"Evidence quote exceeds 1000 characters: {evidence_item.quote[:50]}...")
        return v