name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or master, depending on your default branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Docusaurus build output directory
          # The branch Docusaurus will deploy to. Often gh-pages
          # if you're using the default GitHub Pages setup.
          # If your repository is user/org page, this might be main.
          publish_branch: gh-pages